# Generated by Django 3.1.5 on 2021-04-09 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentCode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('postCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='home.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
