# Generated by Django 3.1.5 on 2021-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210409_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path2',
            field=models.ImageField(default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='file',
            name='path3',
            field=models.ImageField(default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.ImageField(default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
    ]
