# Generated by Django 3.1.5 on 2021-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210409_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path2',
        ),
        migrations.RemoveField(
            model_name='file',
            name='path3',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='reg_date',
            field=models.DateField(null=True, verbose_name='register date'),
        ),
    ]
