# Generated by Django 3.1.5 on 2021-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210409_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commentCode']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['fileCode']},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['reg_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
