# Generated by Django 3.1.5 on 2021-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210507_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testCode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
