# Generated by Django 3.1.5 on 2021-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testCode',
        ),
        migrations.AddField(
            model_name='test',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
