# Generated by Django 3.1.5 on 2021-05-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210507_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
