# Generated by Django 3.1.5 on 2021-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='reg_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentCode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileCode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
