# Generated by Django 3.1.5 on 2021-05-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
    ]
