# Generated by Django 3.1.5 on 2021-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.ImageField(default='post/review_img.png', upload_to='post/%Y/%m/%d'),
        ),
    ]
