# Generated by Django 3.1.5 on 2021-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210514_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.ImageField(default='post/no_image.png', upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post/review_img.png', upload_to='post/%Y/%m/%d'),
        ),
    ]
