# Generated by Django 3.1.5 on 2021-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210514_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
